language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mohammeds96/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true mohammeds96/react-test npm test


after_success:
  - docker build -t mohammeds96/client-server ./frontend
  - docker build -t mohammeds96/api-server ./backend
  - docker build -t mohammeds96/nginx-server ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push mohammeds96/client-server
  - docker push mohammeds96/api-server
  - docker push mohammeds96/nginx-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: products-shop
  env: ProductsShop-env
  bucket_name: elasticbeanstalk-eu-central-1-479537030235
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY