version: '3.7'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/data/app
      - /data/node_modules
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    depends_on:
      - api
      - client
    restart: always
  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gkmgkm123A
      - POSTGRES_DB=capstone